### ISSUE TITLE
PYQ Sensor --> Binary_sensor ?

### ISSUE THREAD

**Issue by Lordxv** [Schnup89/LIVY_RING_G2-Tasmota#19]
Hi, 
vielleicht kann mir jmd weiterhelfen. Ich habe das Problem das in Home Assistant der Bewegungssensor als normaler Sensor erkannt wird und er dafür zahlen Werte erwartet. 
In Home Assistant wird zwar der richtige Wert "True or False" angezeigt aber nicht verarbeitet. 
![image](https://user-images.githubusercontent.com/34307302/174296886-510dd9b3-9ba5-4ccb-8c32-0bf78b8c61c6.png)

Kann ich in tasmota ihm sagen das es ein Binary_sensor ist ?

Viele Grüße und Danke nochmal für das toll Projekt !

**Comment by blautob** [comment]
Ich wollte das so rum lösen. Hatte aber keine Zeit bisher 

https://community.home-assistant.io/t/remove-unit-of-meassurement-from-sensor/414477

**Comment by Lordxv** [comment]
Danke für die Tipps, 
Ich habe es jetzt geschafft mit:
"RULE3 ON PYQ#Movement=true do Publish stat/%topic%/MOTION 1 endon on PYQ#Movement=false do Publish stat/%topic%/MOTION 0 endon"
"Rule3 1"

HomeAssistat in die Configuration.yaml : 
mqtt:
  binary_sensor:
   - name: Ring1 Movement
     state_topic: "stat/tasmota_XXXX/MOTION"
     payload_on: "1"
     payload_off: "0"
     device_class: motion

Jetzt kann ich endlich damit automatisieren ! Danke euch !

**Comment by KrammSteffi** [comment]
vielen Dank Lordxv

Home Assistant hat ne neue Syntax für MQTT
https://community.home-assistant.io/t/new-mqtt-form-new-homeassistant-release-syntax-question/428404

```
mqtt:
  binary_sensor:
    state_topic: "stat/tasmota_xxxxxx/MOTION"
    unique_id: Ring1id_movement
    name: "Ring1 myname movement"
    payload_on: "1"
    payload_off: "0"
    device_class: motion
```
	
	
und mir hilfts wenn die Sensoren gleich nach nem Neustart(leider rebooten meine von Zeit zu Zeit) an sind

```
rule4 
ON system#boot DO POWER1 1 ENDON
ON system#boot DO POWER3 1 ENDON
rule4 1
```
